apiVersion: v1
kind: Namespace
metadata:
  name: squid
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data
  namespace: squid
spec:
  storageClassName: "local-storage"
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /home/litecoin/.litecoin/
  # claimRef:
  #   name: data
  #   namespace: squid
---
apiVersion: v1
kind: Service
metadata:
  name: litecoind
  namespace: squid
  labels:
    app: litecoind
spec:
  ports:
  - port: 80
    name: litecoind
  clusterIP: None
  selector:
    app: litecoind
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: litecoind
  namespace: squid
spec:
  selector:
    matchLabels:
      app: litecoind # has to match .spec.template.metadata.labels
  serviceName: "litecoind"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: litecoind # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: litecoind
        image: localhost:5000/lite-squid:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        # ports:
        # - containerPort: 80
        #   name: web
        volumeMounts:
        - name: data
          mountPath: /home/litecoin/.litecoin
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "local-storage"
      resources:
        requests:
          storage: 1Gi